# Generated by Django 3.1.6 on 2021-04-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Model', max_length=255)),
                ('summary', models.TextField()),
                ('model_file', models.FileField(blank=True, upload_to='ai_models')),
                ('category', models.IntegerField(choices=[(1, 'text'), (2, 'photos'), (3, 'video'), (4, 'nlp'), (5, 'others')], default='text', max_length=1)),
                ('model_image', models.ImageField(blank=True, upload_to='ai_models/images')),
            ],
        ),
    ]
