# Generated by Django 3.1.6 on 2021-04-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='category',
            field=models.IntegerField(choices=[(1, 'text'), (2, 'photos'), (3, 'video'), (4, 'nlp'), (5, 'others')], default='text'),
        ),
    ]
